### PR TITLE
Update to the latest version of FFmpeg that will still play local files

### PR DESCRIPTION
**Pull request by JasonLG1979**
This is still going to require some testing to make sure there are no issues with compatibility or regressions.

Lets see how far up in the versions we can get before it breaks.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Good call @barthalion. @TingPing 3.4.6 works with local files.

**Comment by Erick555** [comment]
I would say that it's safer to match what deb version requires which is current state. Moving to slightly less outdated version won't make much difference.

**Comment by JasonLG1979** [comment]
> I would say that it's safer to [match what deb version requires](https://github.com/flathub/com.spotify.Client/pull/92) which is current state. Moving to slightly less outdated version (but not used anywhere else) won't bring much benefit .

Well my theory was the benefit was upstream bug fixes.

Side note: maybe it's better to group those pending changes into single PR otherwise users would have to re-download spotify (which is 100MB+) over and over.

@TingPing can do what he wants as far as the actual commits if he decides to merge anything. But for testing purposes I didn't think that grouping these PR's together was a good idea since they are unrelated changes.

**Comment by JasonLG1979** [comment]
Some digging and testing tells me that Spotify depends on *libwhatever*.so.57 in FFmpeg. I even tried creating *libwhatever*.so.57 symbolic links that point to the actual .so's and no dice.

@Erick555 libavcodec-extra57 is not available in the current Debian stable it's been superseded by libavcodec-extra58 which would probably not work. So matching what Debian currently uses is not really a valid argument anymore.

The last version of Ubuntu to ship libavcodec-extra57 was 18.04 so again in theory local playback would also be broken in any newer versions which includes the current stable.

3.4.6 is the most up to date version that includes the 57 so's. I don't see any reason why we shouldn't be using the most up to date version possible.

**Comment by JasonLG1979** [comment]
Yep. Local playback is broken on Ubuntu 19.04 with a normal install.

**Comment by JasonLG1979** [comment]
Yet another case of us making them look good by fixing something they broke. Or rather let break.

**Comment by TingPing** [comment]
I agree the latest release that provides the soname is *probably* the best one.

It does really suck that these, lets be honest not very important, updates do require massive redownloads though.

**Comment by JasonLG1979** [comment]
> It does really suck that these, lets be honest not very important, updates do require massive redownloads though.

I kept them separate for testing purposes. There's nothing to stop you from combining them into one commit.

**Comment by JasonLG1979** [comment]
I was just trying to keep everything as up to date as possible. Isn't that one of the points of flatpak? So you're running current stable software regardless of your underlying distro version?

**Comment by JasonLG1979** [comment]
> It does really suck that these, lets be honest not very important, updates do require massive redownloads though.

There's a fair amount of bundled bits in this package you may need to decide on a policy of when they should be updated. The Spotify package itself isn't updated very often so maybe update the bundled bits every so many months or if the Spotify package is updated whichever comes 1st?

**Comment by barthalion** [comment]
It's not about commits per se. As we don't have redistribution rights, we need to use extra-data, meaning that any update to the package means redownloading the deb file.

**Comment by JasonLG1979** [comment]
> It's not about commits per se. As we don't have redistribution rights, we need to use extra-data, meaning that any update to the package means redownloading the deb file.

The alternative is to never update the bundled libs then until the base Spotify package is update? That doesn't happen very often. There will be situations where the bundled libs will become out of date before the base Spotify package. Like I said above. @TingPing may need to come up with a policy as to how often the bundled libs are updated.

**Comment by TingPing** [comment]
This discussion isn't really necessary. The update is fine its just an annoying technical detail of extra-data packages.

**Comment by JasonLG1979** [comment]
@TingPing stupid question but why do we even bundle ffmpeg when we could just use org.freedesktop.Platform.ffmpeg granted if it were ever kept up to date it would break Spotify. (it's currently at 3.4.1) But Spotify can't be the only app that needs the 57 so's why not have a ffmpeg-compat-57 runtime that's frozen at  3.4.6?

**Comment by JasonLG1979** [comment]
libnotify is a similar situation there are a lot of apps that use libnotify for desktop notifications that may not want to pull in a huge runtime just for libnotify (if it's included in another runtime? I maybe the GNOME runtime?) It would allow us to decouple those updates.

**Comment by Erick555** [comment]
`org.freedesktop.Platform.ffmpeg` is available only for freededsktop 1.6 which is EOL. ffmpeg for freedesktop 19.08 is at 4.2.x so not compatible. If app needs older ffmpeg then it has to bundle it like spotify does but it's rather limited to proprietary software.

libnotify is in gnome runtime but moving to it (which is hundreds mb bigger) for just one library would be questionable.

**Comment by JasonLG1979** [comment]
I'm just spitballing.

> `org.freedesktop.Platform.ffmpeg` is available only for freededsktop 1.6 which is EOL. ffmpeg for freedesktop 19.08 is at 4.2.x so not compatible. If app needs older ffmpeg then it has to bundle it like spotify does but it's rather limited to proprietary software.
> 

Fair point at some point even Spotify would have to update to 4.x you would think.

> libnotify is in gnome runtime but moving to it (which is hundreds mb bigger) for just one library would be questionable.

I don't know. I'm willing to bet that there are a lot of apps out there that bundle libnotify just because they don't want to pull in the GNOME runtime which as you said is hundreds of megabytes. I think given the choice they'd probably rather use a libnotify runtime rather then bundle it. That seems like a valid reason for a runtime.

**Comment by Erick555** [comment]
> Fair point at some point even Spotify would have to update to 4.x you would think.

Yes, we could drop ffmpeg then.

> That seems like a valid reason for a runtime.

Maybe. This can't happen for 19.08 though and should be proposed at https://gitlab.com/freedesktop-sdk/freedesktop-sdk . We can't do anything here.

**Comment by JasonLG1979** [comment]
> Maybe. This can't happen for 19.08 though and should be proposed at https://gitlab.com/freedesktop-sdk/freedesktop-sdk . We can't do anything here.

We wouldn't need to split it out just provide a libnotify only runtime for apps that that's all they need,

**Comment by JasonLG1979** [comment]
> Not possible from github ui which is perhaps preferred method for merging things here.

I've collaborated with @TingPing a few times over the years. He doesn't seem like the GUI type when it can be done in a terminal. Regardless he's a pretty smart cookie, I'm sure he can figure it out, lol!!!

**Comment by JasonLG1979** [comment]
If he'd like though I can rebase and merge the 2 branches.

**Comment by TingPing** [comment]
`libnotify` is extremely small and low maintainance, it likely hasn't had a relevant fix this entire decade.

**Comment by JasonLG1979** [comment]
> `libnotify` is extremely small and low maintainance, it likely hasn't had a relevant fix this entire decade. (It also shouldn't go into fdo IMO since its a pretty terrible library)

Again just spitballing.

You know you won't get any argument from me as far as the quality of libnotify. (Blocking I/O eww...)

Yep 0.7.7 > 0.7.8 was mostly switching to meson but there was a couple actual update/fixes. I checked the diff before I put in the PR to make sure there was actually any changes and it wasn't just a version bump.

**Comment by JasonLG1979** [comment]
> I agree the latest release that provides the soname is _probably_ the best one.

Well merge it then,lol!!!

**Pull request merged**
