### PR TITLE
Update to the latest version of FFmpeg

### PR DESCRIPTION
**Pull request by JasonLG1979**
The current version used is a couple years old.

This is still going to require some testing to make sure there are no issues with compatibility or regressions.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
So far so good, no obvious problems and ```--show-console``` doesn't output anymore than the normal garbage.

I'll run this branch for a couple more days though to make sure.

**Comment by TingPing** [comment]
I imagine this doesn't work, test local files, they depend on very specific versions.

**Comment by JasonLG1979** [comment]
Yep. It takes a crap on local files...

**Comment by barthalion** [comment]
ffmpeg 3.4.x may work though.

**Comment by JasonLG1979** [comment]
Let's give 3.4.6 a shot

**Pull request closed without merging**
