### PR TITLE
Updated runtime to 21.08 and others

### PR DESCRIPTION
**Pull request by samy-k97**
Also:
- Updated ffmpeg to 4.1.7
- Updated spotifywm to the latest commit
- Updated shared-modules

### CODE REVIEW

**Comment by lionirdeadman** [comment]
Does that ffmpeg work? I remember ffmpeg being left old because Spotify wouldn't work otherwise.

And if it does, does 4.4 work?

**Comment by lionirdeadman** [comment]
I don't use Spotify but I believe ffmpeg is used for *local* music play, not online play if you could test that?

**Comment by TingPing** [comment]
Just out of curiosity, if you delete ffmpeg do local files work for you?

**Comment by samy-k97** [comment]
Yes, everything works fine without ffmpeg

**Comment by Erick555** [comment]
We may consider removing bundled ffmpeg and use ffmpeg-full extension.

**Comment by Erick555** [comment]
I think spotify gained support for ffmpeg 4.x some time ago so we may potentially remove bundled ffmpeg then use it from runtime + ffmpeg-full extension although we need to check if runtime update it too far in future.

**Comment by TingPing** [comment]
Lets just remove the bundled ffmpeg for now then.

**Pull request merged**
