### PR TITLE
add arch64

### PR DESCRIPTION
**Pull request by chifu1234**

### CODE REVIEW

**Comment by Erick555** [comment]
Spotify doesn't support aarch64

**Comment by chifu1234** [comment]
according to the community post, support should be added this week, let's if they release it ;) https://community.spotify.com/t5/Desktop-Linux/spotify-desktop-for-aarch64-linux/td-p/5495487

**Comment by Erick555** [comment]
I don't know how to interpret this post which looks like coming from user not developer. In either way this PR downloads x86_64 spotify and packs it as aarch64 flatpak which is obviously wrong.

**Comment by TingPing** [comment]
When a stable binary exists please open a PR actually packaging that release.

**Pull request closed without merging**
