### PR TITLE
Convert to yaml

### PR DESCRIPTION
**Pull request by eclipseo**
For reference, https://blogs.gnome.org/alexl/2018/05/04/yamling-the-flathub/

Why do I suggest this: cause it easier to copy paste some stuff from other flatpak, and most of them are in YAML already.

### CODE REVIEW

**Comment by Erick555** [comment]
It break all git history though. How often would you need to copy something here?

**Comment by eclipseo** [comment]
> It break all git history though. How often would you need to copy something here?

How does it break all GIT history? It is still there.

**Comment by Erick555** [comment]
Like [this](https://github.com/eclipseo/com.spotify.Client/blame/yamlize/com.spotify.Client.yml)

**Comment by eclipseo** [comment]
> Like [this](https://github.com/eclipseo/com.spotify.Client/blame/yamlize/com.spotify.Client.yml). it's hard to find from which commit particular code origins.

Yes but you can still access the blame of com.spotify.Client.json in the GIT history. Since this is the first commit of this file, there is only one blame.

**Comment by Erick555** [comment]
Why making things more difficult than they are though? json is same valid as yaml on flathub and it worked fine for past 5 years.

**Comment by TingPing** [comment]
I'm not necessarily against this, but you are opening a lot of PRs at once. So can we start with your other small changes and we can think about this later?

**Comment by TingPing** [comment]
Lets just keep it as is for now.

**Pull request closed without merging**
