### PR TITLE
Automatically detect HiDpi displays

### PR DESCRIPTION
**Pull request by cosimoc**
Use a python xsettings client to read the display scaling factor before
launching Spotify, to be able to launch it with the correct scale
factor.

### CODE REVIEW

**Comment by nedrichards** [comment]
Not a problem now, but this obviously won't work in wayland right? (This isn't a blocker as I assume it'll be >1 year before Spotify gets Wayland given the speed of the Chromium and Electron ecosystem and that it's not merged upstream)

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
lgtm. if a user has overriden the zoom using ctrl+alt +/- then they may be a little startled at the interface size. However that user should know how to use the key combo to get back to a sane UI size.

**Comment by cosimoc** [comment]
@nedrichards It does seem to work fine on wayland fwiw, I developed the patch on my Fedora install which uses wayland.

**Comment by nedrichards** [comment]
Right - but via XWayland since the app isn't getting Wayland permissions, which is fine.

**Pull request merged**
