### PR TITLE
newer client version

### PR DESCRIPTION
**Pull request by kumiokru**
Spotify updated package
-fixed url
-new checksums
-sizes

### CODE REVIEW

**Comment by Barthalion** [comment]
bot, build

**Comment by Barthalion** [comment]
Thanks!

**Comment by TingPing** [comment]
Ugh, we just switched these to the "stable" releases and now this is back to the betas.

**Comment by TingPing** [comment]
Ok ignore that, they did entirely delete the previous series so I guess this went stable.

**Pull request merged**
